#!/usr/bin/env bash

if [ "$1" == "" ]; then
    echo "Usage:"
    echo " undeploy <DIR>"
    exit 1
fi

if [ ! -f "/usr/local/bin/sites_shutdown.sh" ]; then
    cp sites_shutdown.sh /usr/local/bin/sites_shutdown.sh
fi

stow -vv -D -t .. $1
/usr/local/bin/sites_shutdown.sh $1

